#!/usr/bin/env node
/**
 * @file
 * Fake PHPCBF executable for tests.
 */

function getStdin() {
  return new Promise((resolve) => {
    const chunks = [];
    process.stdin.on('data', (chunk) => chunks.push(chunk));
    process.stdin.on('end', () => resolve(Buffer.concat(chunks).toString()));
    if (process.stdin.isTTY) resolve('');
  });
}

getStdin()
  .then((stdin) => {
    console.log(
      JSON.stringify({
        arg: process.argv.slice(1).join(' '),
        stdin,
      }),
    );
  })
  .finally(() => process.exit(1));
